# Generated by Django 2.0.5 on 2018-06-07 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20180607_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
